import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class Agency extends javax.swing.JInternalFrame {
Connection conn = null;
ResultSet rs=null;
PreparedStatement pst= null;
    /**
     * Creates new form Agency
     */
    public Agency() {
        initComponents();
         conn= javaconnect.ConnectDb();
         Update_table();
          Fillcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void Update_table(){
        try{
    String sql="select CustomerID,FirstName,LastName,Gender,PassportID,TAID,TAName from customeradd ";
    pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
    Table2.setModel(DbUtils.resultSetToTableModel(rs));
    }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        
    }
    }
    
     private void Fillcombo(){
     try{
     String sql="select TAid,TAname from agency ";
      pst=conn.prepareStatement(sql);
      rs=pst.executeQuery();
      while(rs.next()){
      String id=rs.getString("TAid");
      imid.addItem(id);
      String name=rs.getString("TAname");
       imtname.addItem(name);
      }
     }
catch(Exception e){
      JOptionPane.showMessageDialog(null,e);
     
     }}
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtpt2 = new javax.swing.JTextField();
        txtln2 = new javax.swing.JTextField();
        txtfn2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        G5 = new javax.swing.JRadioButton();
        G6 = new javax.swing.JRadioButton();
        txtid2 = new javax.swing.JTextField();
        imid = new javax.swing.JComboBox<>();
        imtname = new javax.swing.JComboBox<>();
        addcb = new javax.swing.JButton();
        updatecb = new javax.swing.JButton();
        deletecb = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtsearch = new javax.swing.JTextField();
        bsearch2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txttid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        f1 = new javax.swing.JRadioButton();
        f2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcnt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addtb = new javax.swing.JButton();
        updatetb = new javax.swing.JButton();
        deletetb = new javax.swing.JButton();
        Cancel1 = new javax.swing.JButton();

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "First Name", "Last Name", "Gender", "Passport ID", "TA ID", "TA Name"
            }
        ));
        Table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Table2);

        jPanel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(830, 775));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Last Name");

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Passport ID");

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("TA Name");

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("First Name");

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("TA ID");

        txtpt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpt2ActionPerformed(evt);
            }
        });

        txtfn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfn2ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 51));
        jLabel20.setText("Customer ID");

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Gender");

        buttonGroup2.add(G5);
        G5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        G5.setText("Male");
        G5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(G6);
        G6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        G6.setText("Female");
        G6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G6ActionPerformed(evt);
            }
        });

        imid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imidActionPerformed(evt);
            }
        });

        addcb.setBackground(new java.awt.Color(0, 0, 255));
        addcb.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        addcb.setForeground(new java.awt.Color(255, 255, 255));
        addcb.setText("Add");
        addcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcbActionPerformed(evt);
            }
        });

        updatecb.setBackground(new java.awt.Color(0, 0, 255));
        updatecb.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        updatecb.setForeground(new java.awt.Color(255, 255, 255));
        updatecb.setText("Update");
        updatecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecbActionPerformed(evt);
            }
        });

        deletecb.setBackground(new java.awt.Color(0, 0, 255));
        deletecb.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        deletecb.setForeground(new java.awt.Color(255, 255, 255));
        deletecb.setText("Delete");
        deletecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecbActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(0, 0, 204));
        cancel.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addcb)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpt2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(imid, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imtname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtfn2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtln2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(G5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(G6)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(updatecb)
                        .addGap(65, 65, 65)
                        .addComponent(deletecb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancel)
                        .addGap(43, 43, 43))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtln2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(G5)
                        .addComponent(G6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpt2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imid, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addcb)
                    .addComponent(updatecb)
                    .addComponent(deletecb)
                    .addComponent(cancel))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bsearch2.setBackground(new java.awt.Color(0, 0, 255));
        bsearch2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        bsearch2.setForeground(new java.awt.Color(255, 255, 255));
        bsearch2.setText("Search");
        bsearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsearch2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("TA ID");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("TA Name");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Contact Person");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Gender");

        buttonGroup1.add(f1);
        f1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        f1.setText("Male");
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(f2);
        f2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        f2.setText("Female");
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Email Address");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Contact No.");

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("Agency Details");

        addtb.setBackground(new java.awt.Color(0, 0, 255));
        addtb.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        addtb.setForeground(new java.awt.Color(255, 255, 255));
        addtb.setText("Add");
        addtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtbActionPerformed(evt);
            }
        });

        updatetb.setBackground(new java.awt.Color(0, 0, 255));
        updatetb.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        updatetb.setForeground(new java.awt.Color(255, 255, 255));
        updatetb.setText("Update");
        updatetb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatetbActionPerformed(evt);
            }
        });

        deletetb.setBackground(new java.awt.Color(0, 0, 255));
        deletetb.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        deletetb.setForeground(new java.awt.Color(255, 255, 255));
        deletetb.setText("Delete");
        deletetb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletetbActionPerformed(evt);
            }
        });

        Cancel1.setBackground(new java.awt.Color(0, 0, 255));
        Cancel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Cancel1.setForeground(new java.awt.Color(255, 255, 255));
        Cancel1.setText("Cancel");
        Cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtta, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txttid, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtpn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bsearch2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(f1)
                                .addGap(82, 82, 82)
                                .addComponent(f2))
                            .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addtb)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(updatetb)
                                .addGap(18, 18, 18)
                                .addComponent(deletetb)
                                .addGap(18, 18, 18)
                                .addComponent(Cancel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(txtcnt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsearch2)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txttid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f1)
                    .addComponent(f2)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcnt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addtb)
                    .addComponent(updatetb)
                    .addComponent(deletetb)
                    .addComponent(Cancel1))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpt2ActionPerformed

    private void txtfn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfn2ActionPerformed

    private void G5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G5ActionPerformed
        Gender= "Male";
    }//GEN-LAST:event_G5ActionPerformed

    private void G6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G6ActionPerformed
        Gender="Female";
    }//GEN-LAST:event_G6ActionPerformed

    private void bsearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsearch2ActionPerformed

        try{
            pst=conn.prepareStatement("select TAid,TAname,contactpsn,tgender,email,contact from agency where TAid=?");
            String ide=txtsearch.getText();
            pst.setString(1, ide);
            rs=pst.executeQuery();
            if(rs.next() ==false){
                JOptionPane.showMessageDialog(null,"Sorry, Record is not Available");
                txttid.setText("");
                txtta.setText("");
                txtpn.setText("");
                if(rs.getString("tgender")==("Male")){
                    f1.setSelected(false);
                }else{
                    f2.setSelected(false);
                }
                txtmail.setText("");
                txtcnt.setText("");
                txttid.requestFocus();
            }else{
                String add1=rs.getString("TAid");
                txttid.setText(add1);
                String add2=rs.getString("TAname");
                txtta.setText(add2);
                String add3=rs.getString("contactpsn");
                txtpn.setText(add3);
               
                if(rs.getString("tgender")==("Male")){
                    f1.setSelected(true);
                }else{
                    f2.setSelected(true);
                }
                String add5=rs.getString("email");
                txtmail.setText(add5);
               
                String add6=rs.getString("contact");
                txtcnt.setText(add6);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_bsearch2ActionPerformed

    private void Table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2MouseClicked
        try{
            int row=Table2.getSelectedRow();
            String Table_click=(Table2.getModel().getValueAt(row, 0).toString());
            String sql="select CustomerID,FirstName,LastName,Gender,PassportID,TAID,TAName from customeradd where CustomerID='"+Table_click+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("CustomerID");
                txtid2.setText(add1);
                String add2=rs.getString("FirstName");
                txtfn2.setText(add2);
                String add3=rs.getString("LastName");
                txtln2.setText(add3);
                if((rs.getString("Gender")=="Male")){
                    G5.setSelected(true);
                }else{
                    G6.setSelected(true);
                }
                String add5=rs.getString("PassportID");
                txtpt2.setText(add5);
                String add6=rs.getString("TAID");
                imid.setSelectedItem(add6);
                 String add7=rs.getString("TAName");
                imtname.setSelectedItem(add7);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_Table2MouseClicked

    private void addtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtbActionPerformed
        String id= txttid.getText();
        String ta= txtta.getText();
        String pn= txtpn.getText();
        String email= txtmail.getText();
        String cntno= txtcnt.getText();
       
        try {
           
           
            String sql= ("insert into agency(TAid,TAname,contactpsn,tgender,email,contact) values(?,?,?,?,?,?)");
            pst= conn.prepareStatement(sql);
            pst.setString(1,id);
            pst.setString(2,ta);
            pst.setString(3,pn);
            pst.setString(4,Gender);
           
            pst.setString(5,email);
            pst.setString(6,cntno);
          
            pst.execute();
            
            JOptionPane.showMessageDialog(this,"Travel Agency Registration created..");

        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }

                                           
    }//GEN-LAST:event_addtbActionPerformed

    private void addcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcbActionPerformed
         
        String cid= txtid2.getText();
        String fn= txtfn2.getText();
        String ln= txtln2.getText();
        String pid= txtpt2.getText();
        String taid=imid.getSelectedItem().toString();
        String taname=imtname.getSelectedItem().toString();
        try {
           
           
            String sql= "insert into customeradd(CustomerID,FirstName,LastName,Gender,PassportID,TAID,TAName) values(?,?,?,?,?,?,?)";
            pst= conn.prepareStatement(sql);
            
            pst.setString(1,cid);
            pst.setString(2,fn);
            pst.setString(3,ln);
            pst.setString(4,Gender);
            pst.setString(5,pid);
            pst.setString(6,taid);
            pst.setString(7,taname);
            pst.execute();
            
            JOptionPane.showMessageDialog(this,"Customer Registration created..");

        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
        }
Update_table();
                                           
    }//GEN-LAST:event_addcbActionPerformed

    private void updatetbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatetbActionPerformed
        try{
        String id= txttid.getText();
        String ta= txtta.getText();
        String pn= txtpn.getText();
        String gen=Gender;
        String email= txtmail.getText();
        String cntno= txtcnt.getText();
        
        String sql="update agency set TAid='"+id+"' ,TAname='"+ta+"',contactpsn='"+pn+"',tgender='"+gen+"',email='"+email+"',contact='"+cntno+"' where TAid='"+id+"'";
        pst=conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null,"Travel Agency Details Updated."); 
      }
      catch(Exception e){
      JOptionPane.showMessageDialog(null,e);
      }
    }//GEN-LAST:event_updatetbActionPerformed

    private void updatecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecbActionPerformed
         try{
           
        String cid= txtid2.getText();
        String fn= txtfn2.getText();
        String ln= txtln2.getText();
        String gen=Gender;
        String pid= txtpt2.getText();
         String taid=imid.getSelectedItem().toString();
        String taname=imtname.getSelectedItem().toString();
        
        String sql="update customeradd set CustomerID='"+cid+"' ,FirstName='"+fn+"',LastName='"+ln+"',Gender='"+gen+"',PassportID='"+pid+"',TAID='"+taid+"',TAName=' "+taname+" 'where CustomerID='"+cid+"'";
        pst=conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null,"Customer Details Updated."); 
      }
      catch(Exception e){
      JOptionPane.showMessageDialog(null,e);
      
    }  
         Update_table();
    }//GEN-LAST:event_updatecbActionPerformed

    private void deletetbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletetbActionPerformed
          String sql= "delete from agency where TAid=?";
        
        try{
        pst=conn.prepareStatement(sql);
            pst.setString(1,txttid.getText());
           
        pst.execute();
        JOptionPane.showMessageDialog(null,"Deleted");
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_deletetbActionPerformed

    private void deletecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecbActionPerformed
         String sql= "delete from customeradd where CustomerID=?";
        
        try{
        pst=conn.prepareStatement(sql);
            pst.setString(1,txtid2.getText());
           
        pst.execute();
        JOptionPane.showMessageDialog(null,"Deleted");
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
         Update_table();
    }//GEN-LAST:event_deletecbActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       this.hide();
    }//GEN-LAST:event_cancelActionPerformed

    private void imidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imidActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
         Gender= "Male";
    }//GEN-LAST:event_f1ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
         Gender= "Female";
    }//GEN-LAST:event_f2ActionPerformed

    private void Cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel1ActionPerformed
        this.hide();
    }//GEN-LAST:event_Cancel1ActionPerformed
private String Gender;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel1;
    private javax.swing.JRadioButton G5;
    private javax.swing.JRadioButton G6;
    private javax.swing.JTable Table2;
    private javax.swing.JButton addcb;
    private javax.swing.JButton addtb;
    private javax.swing.JButton bsearch2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancel;
    private javax.swing.JButton deletecb;
    private javax.swing.JButton deletetb;
    private javax.swing.JRadioButton f1;
    private javax.swing.JRadioButton f2;
    private javax.swing.JComboBox<String> imid;
    private javax.swing.JComboBox<String> imtname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtcnt;
    private javax.swing.JTextField txtfn2;
    private javax.swing.JTextField txtid2;
    private javax.swing.JTextField txtln2;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtpn;
    private javax.swing.JTextField txtpt2;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtta;
    private javax.swing.JTextField txttid;
    private javax.swing.JButton updatecb;
    private javax.swing.JButton updatetb;
    // End of variables declaration//GEN-END:variables
}
